[[target]]
name = "pr557977_enable"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["enable"]

[[target]]
name = "pr557977_package"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["package"]

[[target]]
name = "pr557977_openFirewall"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["openFirewall"]

[[target]]
name = "pr557977_settings"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["settings"]

[[target]]
name = "pr557977_settings_HOST"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["settings.HOST"]

[[target]]
name = "pr557977_settings_PORT"
module = "nixos/modules/services/web-apps/elk.nix"
test = "nixos/tests/web-apps/elk.nix"
cfg_ident = "cfg"
option_prefix = ["services", "elk"]
watch = ["settings.PORT"]
