[[target]]
name = "openFirewall-noset"
module = "nixos/modules/demo.nix"
test = "nixos/tests/demo-noset.nix"
cfg_ident = "cfg"
option_prefix = ["services", "demo"]
watch = ["openFirewall"]

[[target]]
name = "port-noset"
module = "nixos/modules/demo.nix"
test = "nixos/tests/demo-noset.nix"
cfg_ident = "cfg"
option_prefix = ["services", "demo"]
watch = ["port"]

[[target]]
name = "package-noset"
module = "nixos/modules/demo.nix"
test = "nixos/tests/demo-noset.nix"
cfg_ident = "cfg"
option_prefix = ["services", "demo"]
watch = ["package"]

